Added "About" box with links
easyScience/easyAppGui pull request #2
Opened 2021-01-29 14:26 UTC by rozyczko

Links and images are defined in the application, so the dialog is technique independent
DAS-288

2021-02-01 10:12 UTC, AndrewSazonov commented on easyAppGui/Components/AboutDialog.qml
> +        spacing: 30
One can use the sizes related to the default font size (EaStyle.Sizes.fontPixelSize * ...). See `easyAppGui/Componenets/ProjectDescriptionDialog.qml` as an example.

2021-02-01 10:39 UTC, AndrewSazonov requested changes

2021-02-01 10:39 UTC, AndrewSazonov commented on easyAppGui/Components/AboutDialog.qml
> +        spacing: 30
One can use the sizes related to the default font size (EaStyle.Sizes.fontPixelSize * ...). See `easyAppGui/Componenets/ProjectDescriptionDialog.qml` as an example.

2021-02-01 10:39 UTC, AndrewSazonov commented on easyAppGui/Components/AboutDialog.qml
> +                } // Image
One can create a new qml component as the base for an image with link.

2021-02-01 10:39 UTC, AndrewSazonov commented on easyAppGui/Components/AboutDialog.qml
> +        }
One can use the EaElements.Label component instead of Text one with the specified font family, size and color.

2021-02-01 10:39 UTC, AndrewSazonov commented on easyAppGui/Components/AboutDialog.qml
> +                        onClicked: Qt.openUrlExternally(EaGlobals.Variables.appUrl)
Instead of using global properties, one can create local ones (appUrl, etc.). See both `easyAppGui/Componenets/ProjectDescriptionDialog.qml` and `easyDiffractionApp/Gui/Pages/Project/ProjectDescriptionDialog.qml` as an example.

2021-02-02 15:27 UTC, AndrewSazonov requested changes

2021-02-02 15:27 UTC, AndrewSazonov commented on easyAppGui/Elements/qmldir
> +LinkedImage 1.0 LinkedImage.qml
Can't find LinkedImage.qml in easyAppGui/Elements

2021-02-02 15:27 UTC, AndrewSazonov commented on easyAppGui/Components/AboutDialog.qml
>              color: "#222"
Theme-dependent color is already defined in EaElements.Label, so it's not needed here.

2021-02-02 15:27 UTC, AndrewSazonov commented on easyAppGui/Components/AboutDialog.qml
>                      Text {
'Text' element can be replaced with 'EaElements.Label'

2021-02-02 15:27 UTC, AndrewSazonov commented on easyAppGui/Components/AboutDialog.qml
>                  spacing: 10
'10' can be replaced with 'EaStyle.Sizes.fontPixelSize

2021-02-02 16:26 UTC, rozyczko commented on easyAppGui/Elements/qmldir
> +LinkedImage 1.0 LinkedImage.qml
Ooops, forgot to commit the file...

2021-02-03 11:36 UTC, AndrewSazonov approved these changes

2021-02-03 11:38 UTC, merged